# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e32b4189c038b2455437b1fbb6cbb884315761eefa703936c8b0a9dd16def3b4f3ffb4e3968bf7c463a64586d96e36ede893df102feeb764efdc047869839655

test:
  secret_key_base: 405c182c323a3ca7175d2306b78d5c7bd946324d7add609ad2269b0f274b0bb18de8de9f1632c1ca4913e3554627ef9e1c89c2aa172549b37ab65b60ba27ad01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
